apiVersion: v1

kind: Pod

metadata:
  name: db-deployment
  namespace: crud-app
  labels:
    app: crud_app
    type: db

spec:

  containers:
    - name: postgres-container
      image: postgres:16
      volumeMounts:
        - mountPath: "/var/www/html"
          name: db-volume
      
      env:
        - name: POSTGRES_DB
          value: postgres
        
        - name: POSTGRES_USER
          value: postgres
        
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret-pass
              key: DB_PASSWORD

  volumes:
    - name: db-volume
      persistentVolumeClaim:
        claimName:  pv1-claim
  
  
    